### PR TITLE
patches: Remove outdated patch

### PR DESCRIPTION
**Pull request by StefanJum**
The patch was:
* Replacing the lua `main` symbol with `lua_main`.
* Removing checking that the given argument was a script, instead
  checking if there is an initrd filesystem present and trying to
  execute it.

The `main` symbol is already replaced in the preprocessing stage by
adding `-Dmain=lua_main` in the `Makefile.uk` flags, so renaming it is
not needed.

Trying to execute the initrd without properly extracting it will
obviously fail, since `lua` will not be able to read the script properly.
This will result in an `malformed number near '0707010..'` error.

The check for initrd is not needed at all, since the fs driver is
transparent for the application, and the script can be accessed as an
usual file, regardell of the fs dreiver (initrd, 9pfs, etc.).

`app-lua` can be run with a script as an argument with one of the following:

```console
/usr/bin/qemu-system-x86_64 \                                                                          
    -fsdev local,id=myid,path="$(pwd)/fs0",security_model=none \
    -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
    -kernel build/app-lua_qemu-x86_64 \
    -nographic -append "helloworld.lua"

```

```console
/usr/bin/qemu-system-x86_64 \                                                                          
    -initrd initrd.cpio \
    -kernel build/app-lua_qemu-x86_64 \
    -nographic -append "helloworld.lua"
```

Signed-off-by: Stefan Jumarea <stefanjumarea02@gmail.com>

### CODE REVIEW

**Review by razvand — COMMENTED** [review]
Thanks, @StefanJum , this works, in conjunction to PR #7. Once @eduardvintila does his review, I will approve it to have it merged.

**Review by eduardvintila — CHANGES_REQUESTED** [review]
This is great, @StefanJum, thank you. You know what's greater? This typo from the last phrase of your commit message:  `regardell of the fs dreiver` 😁

**Comment by StefanJum** [comment]
> This is great, @StefanJum, thank you. You know what's greater? This typo from the last phrase of your commit message: `regardell of the fs dreiver` grin

Wow that was a bad one, fixed :laughing:

**Review by eduardvintila — APPROVED** [review]
All good now 😬 , thanks! 

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
