### PR TITLE
lua/Makefile.uk: Bump to Lua version 5.4.3

### PR DESCRIPTION
**Pull request by FredrikBakken**

### CODE REVIEW

**Review by gabrielmocanu — APPROVED** [review]
Looks good to me. The only problem is with the patch subject line as mentioned above.

Reviewed-by: Mocanu Gabriel <gabi.mocanu98@gmail.com>

**Comment by razvand** [comment]
@FredrikBakken , please add the `lua/Makefile.uk:` prefix to the commit message.

**Comment by FredrikBakken** [comment]
Hi @gabrielmocanu and @razvand! Sorry for my late reply. I have now updated the commit message to include the `lua/Makefile.uk:` prefix. Is it also necessary to remove this from the subject line?

**Comment by gabrielmocanu** [comment]
@razvand  What do you think? I don't know what to say about it.

**Comment by razvand** [comment]
@gabrielmocanu , @FredrikBakken , it's fine. Thanks.

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
