### PR TITLE
Change newlib dependency with musl

### PR DESCRIPTION
**Pull request by JADarius**
This PR changes the C library dependency from newlib to musl.

### CODE REVIEW

**Review by eduardvintila — CHANGES_REQUESTED** [review]
This does the job, thank you. You should include a more descriptive message in the commit description, following the [contribution guidelines](https://unikraft.org/docs/contributing/submitting-changes/)

**Review by eduardvintila — CHANGES_REQUESTED** [review]
Looks good - just update the commit message to use "Change" instead of "change" and I'll be ready to approve 👍🏻

**Review by eduardvintila — APPROVED** [review]
All good, thank you!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Review by StefanJum — CHANGES_REQUESTED** [review]
Thank you @JADarius.
The changes to `patches/` will be overriten by #8, so you can remove them.
Everything looks fine besides that.

**Review by razvand — CHANGES_REQUESTED** [review]
@JADarius, squash the two commits in a single commit. The commit should only be related to the Musl dependency. Use `Config.uk` as commit message prefix. No need to use `lib-lua`, it's implicit.

**Review by StefanJum — APPROVED** [review]
Thanks @JADarius.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
